### ISSUE TITLE
[BUG] Better alignment with REST API: send 500 not 400 if predictor couldn't get loaded

### ISSUE THREAD

**Issue by artem-yushkovsky** [ebhy/budgetml#6]
**Describe the bug**
Hi! first of all, thanks for such a neat tool! :tada: 

It's not a bug, I just thought that sending HTTP 400 is not good when the predictor couldn't get loaded (all `/predict*` routes):

https://github.com/ebhy/budgetml/blob/7ade99c795451656401b3abdbd088b87eb8538eb/server/app/main.py#L96-L105

I think, it's better to use a 5XX server-side error:

- [HTTP 400](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) means that there was a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
- [HTTP 500](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500) means that the server encountered an unexpected condition that prevented it from fulfilling the request. This error response is a generic "catch-all" response. Usually, this indicates the server cannot find a better 5xx error code to response.

**Comment by htahir1** [comment]
Good catch! I pushed it now with [this commit.](https://github.com/ebhy/budgetml/commit/3bcc745c87d9807f28596433a16fa7495061b6ab). Also directly updated the base image so that it gets reflected on future runs (Not the most professional but I did not want to wait for the next release of BudgetML to accommodate this small request :+1:  )
