### ISSUE TITLE
Extra files/scripts in Docker container

### ISSUE THREAD

**Issue by JulesBelveze** [ebhy/budgetml#9]
Hi @htahir1 , thanks for the super handy library !

I am wondering whether or not it is possible to include some extra python file when creating the Docker container?
I am attempting to infer a custom model and thus I need a bunch of files like: checkpoint, model file, config and so on..
I couldn't find anything mentioning this in the docs.

Thanks for your help 😄

**Comment by htahir1** [comment]
Hi @JulesBelveze ! Currently, it is not possible to do this: The way it works is that the container itself does not contain the model or any data - just the environment dependencies and server code. That said, you could always create your own container and pass it in the launch function with the dockerfile_path parameter, if you wanted custom stuff in it. You can then make a copy of the server and add whatever you like in there. Maybe thats a route you might want to explore? Let me know if you need help there.

Another way to do it is to actually download the checkpoint, model_file, config etc that you need in your Predictor's load method and then use it later on. You can easily put all the files you need in a google cloud bucket in the same project and download them, just like the actual predictor_class is downloaded in the server.

Yet another way would be to make modifications to the library itself and that would be more involved. The part which would change is the uploading of the predictor_class to the Bucket and then downloading it subsequently in the startup script of the instance: Most of the code is here. Perhaps you could contribute to the repo with your own design -> Super happy for your contributions!

Hope any/all of this helps! Let me know if you have any further issues -> If you do please feel free to open an issue rather than a discussion as that seems to more fitting on the issue board

**Comment by JulesBelveze** [comment]
Hey @htahir1 
I am trying to go for the first option you suggested as I wanna avoid downloading stuff from a bucket (the checkpoints are quite heavy).. :)
However, I'm not sure I totally get what you're suggesting cause...

I have added a `COPY` instruction to the `template.dockerfile`:
```
FROM us.gcr.io/budgetml/budgetml:base-0.1.0

COPY custom_requirements.txt custom_requirements.txt
COPY /path_to_test_file/test_file.txt test_file.txt

RUN pip install -r custom_requirements.txt
```
and I then pass the path to that file in the `launch_local` method. However, I get an error stating that COPY failed because `no such file or directory`.

I also tried to move the `test_file.txt` into the `tmp` folder but then when calling `launch_local` it seems like the process get stuck here
```
DEBUG:urllib3.connectionpool:http://localhost:None "GET /version HTTP/1.1" 200 560
DEBUG:root:Building docker image..
DEBUG:docker.api.build:Looking for auth config
DEBUG:docker.auth:Looking for auth entry for 'marketplace.gcr.io'
DEBUG:docker.auth:Looking for auth entry for 'asia.gcr.io'
DEBUG:docker.auth:Looking for auth entry for 'us.gcr.io'
DEBUG:docker.auth:Looking for auth entry for 'eu.gcr.io'
DEBUG:docker.auth:Looking for auth entry for 'gcr.io'
DEBUG:docker.auth:Looking for auth entry for 'staging-k8s.gcr.io'
DEBUG:docker.api.build:Sending auth config ('gcr.io', 'eu.gcr.io', 'marketplace.gcr.io', 'asia.gcr.io', 'us.gcr.io', 'staging-k8s.gcr.io')
DEBUG:urllib3.connectionpool:http://localhost:None "POST /v1.39/build?t=budget_local&q=False&nocache=False&rm=False&forcerm=False&pull=False&dockerfile=template.Dockerfile HTTP/1.1" 200 None
```

I would really appreciate if you have any suggestions 😄 

Thanks for your help !

**Comment by JulesBelveze** [comment]
EDIT: After quite a while the second attempt worked, but the build time of the image is weirdly long.. (could be my laptop...)

**Comment by htahir1** [comment]
Ah looks like your local path must not have existed from within the context of the docker build. Glad it works now!

The build time might indeed be long depending on system performance - Not sure if I can suggest an improvement here. Perhaps try slimming your custom requirements? Also you should only build when you are sure everything is working and then hopefully its a one time thing
